name: Publish java libraries
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'wolf-deploy-module1/**'
permissions:
  packages: write
  contents: read
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Setup java for publishing
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Publish to github packages
        run: mvn deploy
        working-directory: 'wolf-deploy-module1'
        env:
          GITHUB_TOKEN: ${{ github.token }}


