name: Publish all java libraries
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'wolf-deploy-module1/**'
jobs:
  publish-module1:
    permissions:
      packages: write
      contents: read
    uses: ./.github/workflows/publishReusable.yml
    secrets: inherit
    with:
      library-path: 'wolf-deploy-module1'


