name: Publish all java libraries
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - wolf-deploy-test
    paths:
      - 'wolf-deploy-module1/**'
      - 'wolf-deploy-module2/**'
jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      module1: ${{ steps.filter.outputs.module1 }}
      module2: ${{ steps.filter.outputs.module2 }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3.0.2
        id: filter
        with:
          filters: |
            module1: 'wolf-deploy-module1/**'
            module2: 'wolf-deploy-module2/**'
      - run: echo "Changes done to these libraries:" >> $GITHUB_STEP_SUMMARY
  publish-module1:
    needs: changes
    permissions:
      packages: write
      contents: read
    env:
      has_changes: ${{ needs.changes.outputs.module1 == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "::notice:: Changes to module1 $has_changes"
          echo "::notice:: Alternate Changes to module1 ${{env.has_changes}}"
      - run: echo "module1" >> $GITHUB_STEP_SUMMARY
        if: env.has_changes
      - uses: actions/checkout@v4
        if: env.has_changes == true
      - uses: ./.github/actions/publish-library
        if: ${{ needs.changes.outputs.module1 == 'true' }}
        with:
          library-path: 'wolf-deploy-module1'
  publish-module2:
    permissions:
      packages: write
      contents: read
    needs: [changes, publish-module1]
    if: ${{ needs.changes.outputs.module2 }}
    uses: ./.github/workflows/publishReusable.yml
    with:
      library-path: 'wolf-deploy-module2'

