name: Publish all java libraries
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'wolf-deploy-module1/**'
permissions:
  packages: write
  contents: read
jobs:
  publish-module1:
    uses: ./.github/workflows/publishReusable.yml
    with:
      library-path: 'wolf-deploy-module1'


