name: Publish all java libraries
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'wolf-deploy-module1/**'
      - 'wolf-deploy-module2/**'
jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      module1: ${{ steps.filter.outputs.module1 }}
      module2: ${{ steps.filter.outputs.module2 }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3.0.2
        id: filter
        with:
          filters: |
            module1: 'wolf-deploy-module1/**'
            module2: 'wolf-deploy-module2/**'
  publish-module1:
    needs: changes
    permissions:
      packages: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - run: echo "::notice Changes to module1 ${{needs.changes.outputs.module1}}"
      - uses: actions/checkout@v4
        if: ${{ needs.changes.outputs.module1 == 'true' }}
      - uses: ./.github/actions/publish-library
        if: ${{ needs.changes.outputs.module1 == 'true' }}
        with:
          library-path: 'wolf-deploy-module1'
  publish-module2:
    permissions:
      packages: write
      contents: read
    needs: [changes, publish-module1]
    if: ${{ needs.changes.outputs.module2 == 'true' }}
    uses: ./.github/workflows/publishReusable.yml
    with:
      library-path: 'wolf-deploy-module2'

